name: CI 

on: 
  push: 
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'
          
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}

      - name: installer les dépendances
        run: pip install -r requirements.txt

      


      - name: Lancer les tests
        run: pytest

  lint:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'
            
      - name: Installation de ruff 
        run: pip install ruff 
      
      - name: Lancer ruff 
        run: ruff check .



