name: CI 

on: 
  push: 
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Python 
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'

      - name: installer les dépendances
        run: pip install flask pytest

      - name: Lancer les tests
        run: pytest

  lint:
    runs-on: ubuntu-latest

    needs: test

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with: 
          python-version: '3.12'
            
      - name: Installation de ruff 
        run: pip install ruff 
      
      - name: Lancer ruff 
        run: ruff check .



